---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    transport:
      name: ssh
      username: vagrant
      password: vagrant
    driver:
      box: bento/centos-7.2
      network:
        - ['private_network', {ip: '192.168.57.13'}]

suites:
  - name: default
    run_list:
      - recipe[cb_dvo_jenkins::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
    driver:
      memory: 1024
      cpus: 1
